# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: SUM
subtitle: 会者定离，一期一祈， 感谢在这与你相遇 
description: ''
author: Yang shuping
language: zh-CN
timezone: ''
email: yangshuping2021@163.com


# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
# URL
url: https://ppxpython.github.io/
root: /
permalink: :title/
#  /posts/:abbrlink/  # **一定要配置好这里，非常重要**
# year/:month/:day/:title/   
permalink_defaults:

# # abbrlink config
# abbrlink:
#   alg: crc32  # 算法：crc16(default) and crc32
#   rep: hex    # 进制：dec(default) and hex

pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks



# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date


# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: tomotoes3
# theme: landscape
# theme: skapp 
theme: shoka  

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'   
  # repo: https://github.com/ppxpython/ppxpython.github.io.git  
  repo: git@github.com:ppxpython/ppxpython.github.io.git  
  branch: master  

#   # feed
# feed:
#   type: atom
#   path: atom.xml
#   limit: 0

# jsonContent:
#   meta: false
#   pages: false
#   posts:
#     title: true
#     date: true
#     path: true
#     text: true
#     raw: false
#     content: false
#     slug: false
#     updated: false
#     comments: false
#     link: false
#     permalink: false
#     excerpt: false
#     categories: false
#     tags: true


# githubEmojis:
#   enable: true
#   className: github-emoji
#   unicode: false
#   styles:
#   localEmojis:

# emoji:
#   enable: true
#   className: github-emoji
#   styles:
#   customEmojis:


markdown:
  render: # 渲染器设置
    html: false # 排除 html 标签
    xhtmlOut: true
    breaks: true
    linkify: true
    typographer: 
    quotes: '“”‘’'
  plugins: # markdown-it 插件设置
  # plugins:
  # - hexo-algoliasearch
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的 class 名称，shoka 主题必须设置成这样
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得太多了"

minify:
  html:
    enable: true
    exclude: # 排除 hexo-feed 用到的模板文件
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    mangle:
      toplevel: true
    output:
    compress:
    exclude:
      - '**/*.min.js'

 
# algolia:
#   appId: #Your appId
#   apiKey: #Your apiKey
#   adminApiKey: #Your adminApiKey
#   chunkSize: 5000
#   indexName: #"shoka"
#   fields:
#     - title #必须配置
#     - path #必须配置
#     - categories #推荐配置
#     - content:strip:truncate,0,2000
#     - gallery
#     - photos
#     - tags


algolia:
  appId: "IKK183PEGG"
  applicationID: "IKK183PEGG"
  apiKey: "3953e85749e69aefe38d9a9d27665d12"
  adminApiKey: "4d33950a93906305d29ea3075b311553"
  chunkSize: 5000
  indexName: "search"
  fields:
    - title #必须配置
    - path   #必须配置
    - categories #推荐配置
    - content:strip:truncate,0,2000
    - gallery
    - photos
    - tags

keywords: 关键词1,关键词2

feed:
    limit: 20
    order_by: "-date"
    tag_dir: false
    category_dir: false
    rss:
        enable: true
        template: "themes/shoka/layout/_alternate/rss.ejs"
        output: "rss.xml"
    atom:
        enable: true
        template: "themes/shoka/layout/_alternate/atom.ejs"
        output: "atom.xml"
    jsonFeed:
        enable: true
        template: "themes/shoka/layout/_alternate/json.ejs"
        output: "feed.json"

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false # edit for Theme.shoka
  line_number: true
  auto_detect: true
  tab_replace: ''
prismjs:
  enable: false # edit for Theme.shoka

# Category & Tag
default_category: uncategorized
category_map: # edit for Theme.shoka
#**************** 一级目录*************************
  计算机科学: computer-science
  #  对应二级目录 
  钉钉小程序: DDapp
# 对应三级目录
  钉钉小程序学习: ddapp-study1
  钉钉小程序常见错误集合: ddapp-error1




#  对应二级目录 
  Java: java
# 对应三级目录
  SpringBoot框架: springboot
  #对应四级目录
  # java
  小白学SpringBoot框架: springboot-study1
  SpringBoot框架常见错误集合: springboot-error1

#  对应二级目录 
  Python: python
# 对应三级目录
  Django框架: django
#对应四级目录
# python 
  零基础学Django框架: course-1
  前端Django中常见的错误集合: django-error1

#  对应二级目录   
  Vue: vue
# 对应三级目录
  Vue框架: vue
  #对应四级目录
  # vue
  初学Vue框架: vue-study1
  前端Vue中常见问题集合: vue-error1
  

# ***************一级目录*********************
  软件测试: software-test
#  对应二级目录
  软件测试知识: testing-knowledge
# 对应三级目录
  单元测试: unit-testing
  集成测试: integration-testing
  系统测试: system-testing
  验收测试: acceptance-testing
  功能测试: functional-testing
  性能测试: performance-testing
  接口测试: api-testing
  安全性测试: security-testing
#对应的四级目录
  #性能:performance-testing
  基准测试: benchmarking
  负载测试: load-test
  压力测试: stress-testing
  稳定性测试: stability-test
  并发测试: concurrent-testing



#  对应二级目录
  自动化测试: automated-testing
# 对应三级目录
  接口自动化测试: Interface-automation-test
  UI自动化测试: ui-automation-test
#对应四级目录框架 Interface-automation-test
  unitTest框架: unittest



#  对应二级目录
  软件测试工具学习: test-tools
# 对应三级目录
  功能测试工具: functional-testing2 
  性能测试工具: performance-testing2 
  接口测试工具: api-testing2 
  压力测试工具: stress-testing2 
  UI测试工具: ui-testing2 
  自动化测试工具: automation-test2 
  移动测试工具: mobile-test2 
#对应四级目录
#接口测试工具
  Postman: postman
  #性能测试工具
  Jmeter: jmeter
  #自动化测试工具
  Selenium: selenium
  Appium: appium


#  对应二级目录
  软件测试项目: test-project 





#******************************************************

  二进制杂谈: note
  计算机程序设计: course-1
  面向对象程序设计-Java语言: course-2



 # ***************一级目录*********************
  心得记录: records

  #对应二级标题
  生活记录: live-record
#对应三级标题
  生活感悟: live-feel
  生活杂记: live-note
  个人博客: live-blog
  新创意点: new-idea



#对应二级标题
  学习记录: study-record
#对应三级标题
  学习心得: study-feel



#对应二级标题
  书籍记录: book-record
#对应三级标题
  书籍心得: book-feel


 # ***************一级目录*********************
  电脑: computer

  #对应二级标题
  电脑配置: win
   #对应三级标题
  win10: win10

   #对应二级标题
  软件配置: app
  #对应三级标题
  安装教程: install

   #对应二级标题
  计算机基础知识: basics
  #对应三级标题
  网络基础: networking
  

   

  # ***************一级目录*********************

 



tag_map:
# Specify the date when the site was setup
since: 2020   # 建站年份


# search:
#   path: search.xml
#   field: post
# Local Search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb


search:
    path: search.xml
    field: post
    format: html
    limit: 10000

local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false

live2d:
  enable: true
  scriptFrom: local
  model:
    use: live2d-widget-model-miku
  display:
    position: right
    width: 140
    height: 260
  mobile:
    show: true
 
